### PR TITLE
PORT: Windows, change default in sgml_open_options

### PR DESCRIPTION
**Pull request by mgondan**

### CODE REVIEW

**Comment by JanWielemaker** [comment]
I doubt this is correct :cry:  Encoding may be provided by the document.  What is the concrete problem we try to solve?

**Comment by mgondan** [comment]
Steps to reproduce: Open swipl-win.exe

Welcome to SWI-Prolog (threaded, 64 bits, version 8.5.9)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit https://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- 
% c:/users/matth/downloads/swipl-8.5.9/packages/sgml/test_sgml compiled into sgml_test 0.00 sec, -6 clauses
?- **test_sgml.**
c:/users/matth/downloads/swipl-8.5.9/packages/sgml/Test/amp.sgml-c:/users/matth/downloads/swipl-8.5.9/packages/sgml/Test/ok/amp.ok
...
c:/users/matth/downloads/swipl-8.5.9/packages/sgml/Test/wcharlong.xml-c:/users/matth/downloads/swipl-8.5.9/packages/sgml/Test/ok/wcharlong.ok
All tests passed
true.

?- **Now, open a shell and do: unix2dos /mnt/c/Users/matth/Downloads/swipl-8.5.9/packages/sgml/Test/estag.sgml**

?- **test_sgml.**
c:/users/matth/downloads/swipl-8.5.9/packages/sgml/Test/estag.sgml-c:/users/matth/downloads/swipl-8.5.9/packages/sgml/Test/ok/estag.ok
WRONG
OK:
[element(oops,[],['<snag attr=2>'])]
ANSWER:
[element(oops,[],['<snag attr=2>\n'])]c:/users/matth/downloads/swipl-8.5.9/packages/sgml/Test/foo.sgml-c:/users/matth/downloads/swipl-8.5.9/packages/sgml/Test/ok/foo.ok

**Comment by mgondan** [comment]
Problem solved, thanks a lot!

**Comment by JanWielemaker** [comment]
Thank you for doing a lot of the work!

**Pull request closed without merging**
